version: '3.9'

services:
  backend:
    build: ../backend
    ports:
      - "8080:8080"
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
  singbox:
    image: ghcr.io/sagernet/sing-box:latest
    command: run -c /etc/sing-box/config.json
    volumes:
      - ./sing-box/config.json:/etc/sing-box/config.json
